name: python
channels: [conda-forge]
dependencies:
  # - python=3.11
  - numpy
  - pandas
  - geopandas
  - rioxarray
  - rasterio
  - pyproj
  - xrspatial
  - gdal
  # - pip
  # - pip:
  #     - maap-py==0.9.16  



# name: python
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - gdal
#   - numpy
#   - pandas
#   - geopandas
#   - rioxarray
#   - rasterio
#   - pyproj
#   - xrspatial


# name: maap-zs
# channels: [conda-forge]
# dependencies:
#   # - python=3.11
#   - numpy
#   - pandas
#   - geopandas
#   - rioxarray
#   - rasterio
#   - pyproj
#   - xrspatial
#   - gdal
#   # - pip
#   # - pip:
#   #     - maap-py==0.9.16  
