name: pangeo
channels:
  - conda-forge
dependencies:
  - anywidget=0.9.13
  - awscli=2.19.4
  - backoff=2.2.1
  - bokeh=3.5.2
  - boto3=1.35.36
  - bottleneck=1.4.2
  - cartopy=0.24.0
  - cdsapi=0.7.4
  - cf_xarray=0.10.0
  - cfgrib=0.9.14.1
  - cython=3.0.11
  - dask-ml=2024.4.4
  - datashader=0.16.3
  - descartes=1.1.0
  - earthaccess=0.11.0
  - earthengine-api=1.4.2
  - eofs=1.4.1
  - erddapy=2.2.3
  - esmpy=8.6.1
  - fastjmd95=0.2.1
  - flox=0.9.14
  - fsspec=2024.10.0
  - gcm_filters=0.5.0
  - gdal=3.9.3
  - geocube=0.7.0
  - geopandas=1.0.1
  - geopy=2.4.1
  - geoviews-core=1.13.0
  - groff=1.22.4
  - h5netcdf=1.4.0
  - h5py=3.12.1
  - hdf5=1.14.3
  - holoviews=1.20.0
  - httpx=0.27.2
  - hvplot=0.11.1
  - intake-esm=2023.11.10
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - intake=2.0.7
  - kerchunk=0.2.6
  - line_profiler=4.1.3
  - lonboard=0.10.3
  - lxml=5.3.0
  - lz4=4.3.3
  - mapclassify=2.8.1
  - matplotlib=3.9.3
  - memory_profiler=0.61.0
  - metpy=1.6.3
  - mizani=0.13.0
  - mpl-scatter-density=0.7
  - nc-time-axis=1.4.1
  - netcdf4=1.7.1
  - numba=0.60.0
  - numbagg=0.8.2
  - numcodecs=0.13.1
  - numpy=2.0.2
  - odc-stac=0.3.10
  - pandarallel=1.6.5
  - pandas=2.2.3
  - pip=24.3.1
  - pyarrow=17.0.0
  - pycamhd=0.7.0
  - pycurl=7.45.3
  - pydap=3.5.1
  - pyogrio=0.10.0
  - pyproj=3.7.0
  - pystac-client=0.8.5
  - pystac=1.11.0
  - python-blosc=1.11.2
  - python=3.12.7
  - rasterio=1.4.2
  - rasterstats=0.20.0
  - rechunker=0.5.2
  - requests=2.32.3
  - rio-cogeo=5.3.6
  - rioxarray=0.17.0
  - rtree=1.3.0
  - s3fs=2024.10.0
  - satpy=0.53.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely=2.0.6
  - sliderule=4.8.6
  - sparse=0.15.4
  - stackstac=0.5.1
  - statsmodels=0.14.4
  - tiledb-py=0.32.5
  - timezonefinder=6.5.4
  - tqdm=4.67.0
  - unidecode=1.3.8
  - unzip=6.0
  - xarray-datatree=0.0.14
  - xarray-spatial=0.4.0
  - xarray=2024.10.0
  - xarrayutils=2.0.1
  - xbatcher=0.4.0
  - xclim=0.53.1
  - xcube=1.7.1
  - xesmf=0.8.8
  - xgboost=2.1.2
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xmip=0.7.2
  - xmitgcm=0.5.2
  - xmltodict=0.13.0
  - xpublish=0.3.3
  - xrft=1.0.1
  - zarr=2.18.3
  - black=24.10.0
  - folium=0.18.0
  - gh-scoped-creds=4.1
  - gh=2.61.0
  - git-lfs=3.5.1
  - gitpython=3.1.43
  - ipyevents=2.0.2
  - ipyleaflet=0.19.2
  - ipytree=0.2.2
  - ipywidgets=8.1.5
  - jupyter-panel-proxy=0.1.0
  - jupyter_server=2.12.5
  - jupyterlab-git=0.50.2
  - jupyterlab=4.3.0
  - jupyterlab_widgets=3.0.13
  - nb_conda=2.2.1
  - nb_conda_kernels=2.5.1
  - nbstripout=0.8.0
  - nodejs=22.11.0
  - pangeo-notebook=2024.11.11
  - plotly=5.24.1
  - plotnine=0.14.3
  - pydantic=2.9.2
  - python-gist=0.10.6
  - python-graphviz=0.20.3
  - rise=5.7.1
  - snakeviz=2.2.0
  - xarray_leaflet=0.2.3
variables:
  TITILER_STAC_ENDPOINT: https://titiler-stac.maap-project.org/
  TITILER_ENDPOINT: https://titiler.maap-project.org/
  STAC_CATALOG_NAME: MAAP STAC
  STAC_CATALOG_URL: https://stac.maap-project.org/
  STAC_BROWSER_URL: https://stac-browser.maap-project.org/
